[package]
name = "tuiserial"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
serialport = "4.3"
crossterm = "0.28"
tokio = { version = "1.40", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
color-eyre = "0.6"
